ecommerce/carts/urls.py
from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
)

urlpatterns = [
    path('',cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
] 

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from accounts.views import login_page, register_page, guest_register_view
from .views import (
    home_page, 
    about_page, 
    contact_page, 
)

urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register'),
    path('admin/', admin.site.urls),
    
    path('products/', include(("products.urls", "products"),namespace="products")),
    path('search/', include(("search.urls", "search"), namespace="search")),


    path('cart/', include(("carts.urls", "carts"),namespace="cart")),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path

from .views import (
    ProductListView, 
    ProductDetailSlugView,
)

urlpatterns = [
    path('',ProductListView.as_view(), name='list'),
    path('<slug:slug>/',ProductDetailSlugView.as_view(), name='detail'),
] 

ecommerce/templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

ecommerce/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

ecommerce/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
<div class="container">
  <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %}{{brand_name}}{% else %} Ecommerce {% endif %}</a>
  {% comment %} <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top"> {% endcomment %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>

      {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
            <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{{ register_url }}">Register</a>
        </li>

        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
      {% endif %}

      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i> </a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html'%}
  </div>
</div>
</nav>